version: 2

project_name: spas

builds:
  - id: spas
    main: .
    binary: spas
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w
      - -X github.com/getspas/spas/internal/version.Version={{ .Version }}
      - -X github.com/getspas/spas/internal/version.Commit={{ .FullCommit }}
      - -X github.com/getspas/spas/internal/version.Date={{ .CommitDate }}

archives:
  - id: release-archives
    ids:
      - spas
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^Merge"
      - "^ci:"
      - "^test:"

release:
  draft: true
  prerelease: auto
  name_template: "SPAS {{ .Tag }}"
