#!/usr/bin/env bash
# Publish the approved recipes attached to the latest stable SPAS release.
set -euo pipefail
: "${GH_TOKEN:?Set DISTRIBUTION_TOKEN for the channel repositories}"
[[ "$TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit 1
gh release view "$TAG" --repo "$GITHUB_REPOSITORY" --json isDraft,isPrerelease \
  --jq '(.isDraft == false) and (.isPrerelease == false)' | grep -qx true
latest=$(gh release view --repo "$GITHUB_REPOSITORY" --json tagName --jq .tagName)
if [[ "$TAG" != "$latest" ]]; then
  echo "Skipping $TAG: $latest is the current release."
  exit 0
fi
gh release download "$TAG" --repo "$GITHUB_REPOSITORY" --pattern "$PATTERN" --dir recipes
for recipe in recipes/*; do
  gh attestation verify "$recipe" --repo "$GITHUB_REPOSITORY" \
    --signer-workflow "$GITHUB_REPOSITORY/.github/workflows/release.yml" --source-ref "refs/tags/$TAG"
done
gh auth setup-git
git clone --depth=1 --filter=blob:none --sparse \
  --config core.autocrlf=false --config core.eol=lf \
  "https://github.com/getspas/$REPOSITORY.git" channel
git -C channel config user.name 'github-actions[bot]'
git -C channel config user.email '41898282+github-actions[bot]@users.noreply.github.com'
git -C channel sparse-checkout set "$DIRECTORY"
if [[ "$CHANNEL" == winget ]]; then
  branch="codex/spas-$TAG"
  git -C channel fetch --depth=1 --filter=blob:none https://github.com/microsoft/winget-pkgs.git master
  git -C channel switch -c "$branch" FETCH_HEAD
  target="$DIRECTORY/${TAG#v}"
  if git -C channel ls-tree --name-only HEAD "$target" | grep -q .; then
    echo "WinGet already contains $TAG."
    exit 0
  fi
else
  branch=main
  target="$DIRECTORY"
  git -C channel rm --ignore-unmatch .spas-release.json
fi
mkdir -p "channel/$target"
cp recipes/* "channel/$target/"
git -C channel add -- "$target"
if git -C channel diff --cached --quiet; then
  echo "$CHANNEL already contains this release."
  exit 0
fi
git -C channel commit -m "chore: update SPAS to $TAG"
if [[ "$CHANNEL" == winget ]] && git -C channel ls-remote --exit-code origin "refs/heads/$branch" > /dev/null; then
  git -C channel fetch --depth=1 origin "$branch"
  git -C channel diff --exit-code HEAD FETCH_HEAD -- "$target"
else
  git -C channel push origin "HEAD:$branch"
fi
if [[ "$CHANNEL" == winget ]]; then
  existing=$(gh pr list --repo microsoft/winget-pkgs --head "getspas:$branch" --state all --json url --jq '.[0].url // empty')
  if [[ -n "$existing" ]]; then
    echo "$existing"
    exit 0
  fi
  printf 'Adds SPAS %s portable ZIP installers for x64 and ARM64. Recipes are generated by GoReleaser and verified against the published release attestation.\n' "${TAG#v}" > pr-body.md
  jq -n --arg title "New version: GetSPAS.SPAS ${TAG#v}" --arg head "getspas:$branch" \
    --rawfile body pr-body.md \
    '{title:$title,head:$head,head_repo:"winget-pkgs",base:"master",body:$body,maintainer_can_modify:true}' > pr-request.json
  gh api --method POST repos/microsoft/winget-pkgs/pulls --input pr-request.json --jq .html_url
fi
