#!/usr/bin/env bash
# Publish the attested recipes generated for the latest stable SPAS release.
set -euo pipefail
: "${GH_TOKEN:?Set DISTRIBUTION_TOKEN for the channel repositories}"
: "${RELEASE_READ_TOKEN:?Set the repository token for release workflow artifacts}"
[[ "$TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit 1
gh release view "$TAG" --repo "$GITHUB_REPOSITORY" --json isDraft,isPrerelease \
  --jq '(.isDraft == false) and (.isPrerelease == false)' | grep -qx true
latest=$(gh release view --repo "$GITHUB_REPOSITORY" --json tagName --jq .tagName)
if [[ "$TAG" != "$latest" ]]; then
  echo "Skipping $TAG: $latest is the current release."
  exit 0
fi
# Select the tagged build, not the newest workflow run, which may belong to another release.
release_commit=$(GH_TOKEN="$RELEASE_READ_TOKEN" gh api "repos/$GITHUB_REPOSITORY/commits/$TAG" --jq .sha)
release_run=$(GH_TOKEN="$RELEASE_READ_TOKEN" gh run list --repo "$GITHUB_REPOSITORY" \
  --workflow release.yml --event push --branch "$TAG" --commit "$release_commit" \
  --status success --limit 1 --json databaseId --jq '.[0].databaseId // empty')
if [[ -z "$release_run" ]]; then
  echo "No successful release workflow found for $TAG." >&2
  exit 1
fi
GH_TOKEN="$RELEASE_READ_TOKEN" gh run download "$release_run" --repo "$GITHUB_REPOSITORY" \
  --name package-manager-recipes --dir recipes
# upload-artifact preserves paths relative to dist; WinGet includes the version directory.
recipe_directory="recipes/$CHANNEL/$DIRECTORY"
if [[ "$CHANNEL" == winget ]]; then
  recipe_directory+="/${TAG#v}"
fi
for recipe in "$recipe_directory/"*; do
  gh attestation verify "$recipe" --repo "$GITHUB_REPOSITORY" \
    --signer-workflow "$GITHUB_REPOSITORY/.github/workflows/release.yml" \
    --source-ref "refs/tags/$TAG" --source-digest "$release_commit"
done
gh auth setup-git
if [[ "$CHANNEL" == winget ]]; then
  # Clone after synchronization so the submission branch starts from current upstream master.
  gh repo sync "getspas/$REPOSITORY" --source microsoft/winget-pkgs --branch master
fi
git clone --depth=1 --filter=blob:none --sparse \
  --config core.autocrlf=false --config core.eol=lf \
  "https://github.com/getspas/$REPOSITORY.git" channel
git -C channel config user.name 'github-actions[bot]'
git -C channel config user.email '41898282+github-actions[bot]@users.noreply.github.com'
git -C channel sparse-checkout set "$DIRECTORY"
if [[ "$CHANNEL" == winget ]]; then
  branch="codex/spas-$TAG"
  git -C channel switch -c "$branch"
  target="$DIRECTORY/${TAG#v}"
  if git -C channel ls-tree --name-only HEAD "$target" | grep -q .; then
    echo "WinGet already contains $TAG."
    exit 0
  fi
else
  branch=main
  target="$DIRECTORY"
  git -C channel rm --ignore-unmatch .spas-release.json
fi
mkdir -p "channel/$target"
cp "$recipe_directory/"* "channel/$target/"
git -C channel add -- "$target"
if git -C channel diff --cached --quiet; then
  echo "$CHANNEL already contains this release."
  exit 0
fi
git -C channel commit -m "chore: update SPAS to $TAG"
if [[ "$CHANNEL" == winget ]] && git -C channel ls-remote --exit-code origin "refs/heads/$branch" > /dev/null; then
  git -C channel fetch --depth=1 origin "$branch"
  git -C channel diff --exit-code HEAD FETCH_HEAD -- "$target"
else
  git -C channel push origin "HEAD:$branch"
fi
if [[ "$CHANNEL" == winget ]]; then
  # REST accepts owner:branch; gh pr list's --head filter accepts only the branch name.
  existing=$(gh api --method GET repos/microsoft/winget-pkgs/pulls \
    -f state=all -f "head=getspas:$branch" --jq '.[0].html_url // empty')
  if [[ -n "$existing" ]]; then
    echo "$existing"
    exit 0
  fi
  printf 'Adds SPAS %s portable executables for x64 and ARM64. Recipes are generated by GoReleaser and verified against the published release attestation.\n' "${TAG#v}" > pr-body.md
  jq -n --arg title "New version: GetSPAS.SPAS ${TAG#v}" --arg head "getspas:$branch" \
    --rawfile body pr-body.md \
    '{title:$title,head:$head,head_repo:"winget-pkgs",base:"master",body:$body,maintainer_can_modify:true}' > pr-request.json
  gh api --method POST repos/microsoft/winget-pkgs/pulls --input pr-request.json --jq .html_url
fi
